### ISSUE TITLE
take a peek at mine - fccvotingappwithtwitter 

### ISSUE THREAD

**Issue by MatthiasLiszt** [DDCreationStudios/votingApp#35]
https://github.com/MatthiasLiszt/fccvotingappwithtwitter

Sorry, for abusing the issue function for that ... 
plz, suggest a better way and I hope you can somehow erase this issue

**Comment by Createdd** [comment]
Wow @MatthiasLiszt  that looks solid! If you want to present or talk about it at the FFC meetup let me know! Iam pretty sure that's interesting for a lot of people- especially FCC users.  Great work! 
And no problem that you are using the issue here. I will update the whole repo soon :)
