### ISSUE TITLE
app.js ... unusal ES6 code instead of expected Node.js code 

### ISSUE THREAD

**Issue by MatthiasLiszt** [DDCreationStudios/votingApp#60]
the src/app.js is executed but it runs into unusal ES6 code ... 
I amsure node.js wants its own code and usual for node.js that looks like 

var express  = require('express');
var app      = express();
var port     = process.env.PORT || 5000;

while you use 

import express from 'express';
import constants from './config/constants';
import './config/database';
....

and as I expected I get the error 
/media/nadja/SAMSUNG/GitSudan/votingApp/src/app.js:2
import express from 'express';
^^^^^^
SyntaxError: Unexpected token import

Why not doing it the usual way and getting the app done in some days ... 

Please, use ES6 for your react/redux frontend stuff but at least do the node.js part the usual way

sorry, it was just too puzzling for me

**Comment by Createdd** [comment]
THanks a lot! I used it primarely  for training purposes. However, I don't see a downside using the newer syntax. And especially in this application should not make any difference? Am I right?
